---
application:
  name: "keeper-website"
  project: "keeper-website"
  organization: "QoveryCommunity"
  publicly_accessible: true
databases:
- type: "POSTGRESQL"
  name: "keeper-database"
  version: "12"
routers:
- name: "keeper-website"
  routes:
  - application_name: "keeper-website"
    paths:
    - /*
