---
application:
  name: "keeper-website"
  project: "keeper-website"
  organization: "QoveryCommunity"
  publicly_accessible: true
databases:
- type: "POSTGRESQL"
  name: "keeper-database"
  version: "12"
routers:
- name: "main-keeper-website"
  custom_domains:
    - branch: master
      domain: travispaquette.com
  routes:
  - application_name: "keeper-website"
    paths:
    - /*
