version: '3.9'

services:
  app:
    build: .
    depends_on:
      - db
    environment:
      FLASK_APP: keeper-website/app.py
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:password@db/yahoofantasy
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./:/usr/src/app
    restart: always

  db:
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: yahoofantasy
    image: postgres:latest
    networks:
      - default
    ports:
      - 5405:5432
    restart: always
    volumes:
      - ./.database:/var/lib/postgresql/data